fix: improve checks

diff --git a/bin/launch b/bin/launch
--- a/bin/launch
+++ b/bin/launch
@@ -57,13 +57,13 @@ main() {
         exit 1
     fi
 
-    if ! command -v button-handler >/dev/null 2>&1; then
-        echo "button-handler binary not found."
+    if ! command -v set-brightness >/dev/null 2>&1; then
+        echo "set-brightness binary not found."
         exit 1
     fi
 
-    if ! command -v set-brightness >/dev/null 2>&1; then
-        echo "set-brightness binary not found."
+    if ! command -v button-handler >/dev/null 2>&1; then
+        echo "button-handler binary not found."
         exit 1
     fi
 
@@ -78,6 +78,7 @@ main() {
     fi
 
     chmod +x "$BIN_DIR/$PLATFORM/minui-presenter"
+    chmod +x "$BIN_DIR/$PLATFORM/set-brightness"
     chmod +x "$BIN_DIR/$architecture/button-handler"
     chmod +x "$BIN_DIR/shutdown"
     chmod +x "$BIN_DIR/suspend"
