refactor: no longer use pid

diff --git a/bin/launch b/bin/launch
--- a/bin/launch
+++ b/bin/launch
@@ -70,28 +70,34 @@ main() {
         exit 1
     fi
 
-    EMULATOR_BIN="$1"
-    EMULATOR_PROCESS_PID=""
-    for _ in $(seq 1 10); do
-        echo "Waiting for $EMULATOR_BIN to start..."
-        EMULATOR_PROCESS_PID=$(pgrep "$EMULATOR_BIN" | head -n 1)
-        if [ -n "$EMULATOR_PROCESS_PID" ] && kill -0 "$EMULATOR_PROCESS_PID" 2>/dev/null; then
-            break
-        fi
-        sleep 1
-    done
-    if [ -z "$EMULATOR_PROCESS_PID" ] || ! kill -0 "$EMULATOR_PROCESS_PID" 2>/dev/null; then
-        echo "Emulator process $EMULATOR_BIN not found."
-        exit 1
-    fi
+    # EMULATOR_BIN="$1"
+    # EMULATOR_PROCESS_PID=""
+    # for _ in $(seq 1 10); do
+    #     echo "Waiting for $EMULATOR_BIN to start..."
+    #     EMULATOR_PROCESS_PID=$(pgrep "$EMULATOR_BIN" | head -n 1)
+    #     if [ -n "$EMULATOR_PROCESS_PID" ] && kill -0 "$EMULATOR_PROCESS_PID" 2>/dev/null; then
+    #         break
+    #     fi
+    #     sleep 1
+    # done
+    # if [ -z "$EMULATOR_PROCESS_PID" ] || ! kill -0 "$EMULATOR_PROCESS_PID" 2>/dev/null; then
+    #     echo "Emulator process $EMULATOR_BIN not found."
+    #     exit 1
+    # fi
 
-    echo "$EMULATOR_PROCESS_PID" > /tmp/emulator_pid
-    echo "Emulator PID: $EMULATOR_PROCESS_PID"
+    # echo "$EMULATOR_PROCESS_PID" > /tmp/emulator_pid
+    # echo "Emulator PID: $EMULATOR_PROCESS_PID"
+
+    touch /tmp/no_pid
 
     button-handler &
     HANDLER_PROCESS_PID=$!
 
-    while kill -0 "$EMULATOR_PROCESS_PID" 2>/dev/null; do
+    # while kill -0 "$EMULATOR_PROCESS_PID" 2>/dev/null; do
+    #     sleep 1
+    # done
+
+    while [ -f /tmp/no_pid ]; do
         sleep 1
     done
 }
diff --git a/bin/suspend b/bin/suspend
--- a/bin/suspend
+++ b/bin/suspend
@@ -17,21 +17,21 @@ main() {
     fi
     chmod +x "$SYSTEM_SUSPEND_SCRIPT"
 
-    if [ -f /tmp/emulator_pid ]; then
-        PROCESS_PID=$(cat /tmp/emulator_pid)
-    else
-        echo "Emulator PID file not found."
-        exit 1
-    fi
+    # if [ -f /tmp/emulator_pid ]; then
+    #     PROCESS_PID=$(cat /tmp/emulator_pid)
+    # else
+    #     echo "Emulator PID file not found."
+    #     exit 1
+    # fi
 
-    if [ -z "$PROCESS_PID" ] || ! kill -0 "$PROCESS_PID" 2>/dev/null; then
-        echo "Emulator process $PROCESS_PID not found."
-        exit 1
-    fi
+    # if [ -z "$PROCESS_PID" ] || ! kill -0 "$PROCESS_PID" 2>/dev/null; then
+    #     echo "Emulator process $PROCESS_PID not found."
+    #     exit 1
+    # fi
 
-    kill -STOP "$PROCESS_PID" || true
+    #kill -STOP "$PROCESS_PID" || true
     "$SYSTEM_SUSPEND_SCRIPT"
-    kill -CONT "$PROCESS_PID" || true
+    #kill -CONT "$PROCESS_PID" || true
 }
 
 main "$@"
