feat: support running without pid

diff --git a/bin/launch b/bin/launch
--- a/bin/launch
+++ b/bin/launch
@@ -14,7 +14,8 @@ cleanup() {
         kill "$HANDLER_PROCESS_PID" || true
         wait "$HANDLER_PROCESS_PID" || true
     fi
-    rm -f /tmp/emulator_pid
+    rm -f /tmp/power_control_emulator_pid
+    rm -f /tmp/power_control_no_pid
 }
 
 main() {
@@ -65,41 +66,44 @@ main() {
     chmod +x "$BIN_DIR/shutdown"
     chmod +x "$BIN_DIR/suspend"
 
-    # if [ "$#" -ne 1 ]; then
-    #     echo "Usage: $0 <emulator-binary>"
-    #     exit 1
-    # fi
+    if [ "$#" -eq 0 ]; then
+        echo "Emulator process not specified. Creating a dummy PID file."
+        touch /tmp/power_control_no_pid
+    elif [ "$#" -eq 1 ]; then
+        EMULATOR_BIN="$1"
+        EMULATOR_PROCESS_PID=""
+        for _ in $(seq 1 10); do
+            echo "Waiting for $EMULATOR_BIN to start..."
+            EMULATOR_PROCESS_PID=$(pgrep "$EMULATOR_BIN" | head -n 1)
+            if [ -n "$EMULATOR_PROCESS_PID" ] && kill -0 "$EMULATOR_PROCESS_PID" 2>/dev/null; then
+                break
+            fi
+            sleep 1
+        done
+        if [ -z "$EMULATOR_PROCESS_PID" ] || ! kill -0 "$EMULATOR_PROCESS_PID" 2>/dev/null; then
+            echo "Emulator process $EMULATOR_BIN not found."
+            exit 1
+        fi
 
-    # EMULATOR_BIN="$1"
-    # EMULATOR_PROCESS_PID=""
-    # for _ in $(seq 1 10); do
-    #     echo "Waiting for $EMULATOR_BIN to start..."
-    #     EMULATOR_PROCESS_PID=$(pgrep "$EMULATOR_BIN" | head -n 1)
-    #     if [ -n "$EMULATOR_PROCESS_PID" ] && kill -0 "$EMULATOR_PROCESS_PID" 2>/dev/null; then
-    #         break
-    #     fi
-    #     sleep 1
-    # done
-    # if [ -z "$EMULATOR_PROCESS_PID" ] || ! kill -0 "$EMULATOR_PROCESS_PID" 2>/dev/null; then
-    #     echo "Emulator process $EMULATOR_BIN not found."
-    #     exit 1
-    # fi
-
-    # echo "$EMULATOR_PROCESS_PID" > /tmp/emulator_pid
-    # echo "Emulator PID: $EMULATOR_PROCESS_PID"
-
-    touch /tmp/no_pid
+        echo "$EMULATOR_PROCESS_PID" > /tmp/power_control_emulator_pid
+        echo "Emulator PID: $EMULATOR_PROCESS_PID"
+    else
+        echo "Usage: $0 <emulator-binary>"
+        exit 1
+    fi
 
     button-handler &
     HANDLER_PROCESS_PID=$!
 
-    # while kill -0 "$EMULATOR_PROCESS_PID" 2>/dev/null; do
-    #     sleep 1
-    # done
-
-    while [ -f /tmp/no_pid ]; do
-        sleep 1
-    done
+    if [ -n "$EMULATOR_PROCESS_PID" ]; then
+        while kill -0 "$EMULATOR_PROCESS_PID" 2>/dev/null; do
+            sleep 1
+        done
+    else
+        while [ -f /tmp/power_control_no_pid ]; do
+            sleep 1
+        done
+    fi
 }
 
 main "$@"
diff --git a/bin/shutdown b/bin/shutdown
--- a/bin/shutdown
+++ b/bin/shutdown
@@ -26,19 +26,19 @@ show_message() {
 }
 
 main() {
-    # if [ -f /tmp/emulator_pid ]; then
-    #     PROCESS_PID=$(cat /tmp/emulator_pid)
-    # else
-    #     echo "Emulator PID file not found."
-    #     exit 1
-    # fi
-
-    # if [ -z "$PROCESS_PID" ] || ! kill -0 "$PROCESS_PID" 2>/dev/null; then
-    #     echo "Emulator process $PROCESS_PID not found."
-    #     exit 1
-    # fi
-
-    # kill "$PROCESS_PID" || true
+    if [ -f /tmp/power_control_emulator_pid ]; then
+        PROCESS_PID=$(cat /tmp/emulator_pid)
+        if [ -z "$PROCESS_PID" ] || ! kill -0 "$PROCESS_PID" 2>/dev/null; then
+            echo "Emulator process $PROCESS_PID not found."
+            exit 1
+        fi
+        kill "$PROCESS_PID" || true
+    elif [ -f /tmp/power_control_no_pid ]; then
+        echo "Dummy PID file found. No emulator process to kill."
+    else
+        echo "Emulator PID file not found."
+        exit 1
+    fi
 
     show_message "Powering off" forever
 
