feat: add tracker script checks

diff --git a/bin/shutdown b/bin/shutdown
--- a/bin/shutdown
+++ b/bin/shutdown
@@ -37,6 +37,12 @@ shutdown_system() {
 }
 
 main() {
+    if [ ! -f "$BIN_DIR/tracker" ]; then
+        echo "tracker script not found."
+        exit 1
+    fi
+    chmod +x "$BIN_DIR/tracker"
+
     if [ -f /tmp/powercontrol-emulator-pid ]; then
         PROCESS_PID=$(cat /tmp/emulator_pid)
         echo "Emulator PID file found. Killing the emulator process with PID: $PROCESS_PID"
diff --git a/bin/suspend b/bin/suspend
--- a/bin/suspend
+++ b/bin/suspend
@@ -50,15 +50,23 @@ fallback_suspend() {
     if [ ! -f /tmp/powercontrol-suspend-active ]; then
         echo "Pausing emulator process with PID: $PID"
         kill -STOP "$PID" || true
+        tracker stop
         touch /tmp/powercontrol-suspend-active
     else
         echo "Resuming emulator process with PID: $PID"
         kill -CONT "$PID" || true
+        tracker start
         rm -f /tmp/powercontrol-suspend-active
     fi
 }
 
 main() {
+    if [ ! -f "$BIN_DIR/tracker" ]; then
+        echo "tracker script not found."
+        exit 1
+    fi
+    chmod +x "$BIN_DIR/tracker"
+
     if [ -f /tmp/powercontrol-emulator-pid ]; then
         PROCESS_PID=$(cat /tmp/emulator_pid)
         echo "Emulator PID file found. Killing the emulator process with PID: $PROCESS_PID"
