feat: support running without pid (#13)

diff --git a/bin/suspend b/bin/suspend
--- a/bin/suspend
+++ b/bin/suspend
@@ -17,21 +17,23 @@ main() {
     fi
     chmod +x "$SYSTEM_SUSPEND_SCRIPT"
 
-    if [ -f /tmp/emulator_pid ]; then
+    if [ -f /tmp/power_control_emulator_pid ]; then
+        echo "Emulator PID file found. Stopping the emulator process."
         PROCESS_PID=$(cat /tmp/emulator_pid)
+        if [ -z "$PROCESS_PID" ] || ! kill -0 "$PROCESS_PID" 2>/dev/null; then
+            echo "Emulator process $PROCESS_PID not found."
+            exit 1
+        fi
+        kill -STOP "$PROCESS_PID" || true
+        "$SYSTEM_SUSPEND_SCRIPT"
+        kill -CONT "$PROCESS_PID" || true
+    elif [ -f /tmp/power_control_no_pid ]; then
+        echo "Dummy PID file found. No emulator process to suspend."
+        "$SYSTEM_SUSPEND_SCRIPT"
     else
         echo "Emulator PID file not found."
         exit 1
     fi
-
-    if [ -z "$PROCESS_PID" ] || ! kill -0 "$PROCESS_PID" 2>/dev/null; then
-        echo "Emulator process $PROCESS_PID not found."
-        exit 1
-    fi
-
-    kill -STOP "$PROCESS_PID" || true
-    "$SYSTEM_SUSPEND_SCRIPT"
-    kill -CONT "$PROCESS_PID" || true
 }
 
 main "$@"
